package sgms.ui;

import javax.swing.JOptionPane;
import sgms.util.CredentialManager;

/**
 * @author Jacques Smit
 *
 * The ForgotPasswordPage class allows users to reset their password. It
 * requires administrator password for authorization.
 */
public class ForgotPasswordPage extends javax.swing.JFrame {

    private CredentialManager credentialManager;

    /**
     * Initializes the ForgotPasswordPage and sets up the CredentialManager.
     */
    public ForgotPasswordPage() {
        initComponents();
        credentialManager = new CredentialManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLillyHouseSchoolLibrary = new javax.swing.JLabel();
        jLabelEnterRequiredDetails = new javax.swing.JLabel();
        jLabelResetPassword = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelNewPassword = new javax.swing.JLabel();
        jPasswordFieldNewPassword = new javax.swing.JPasswordField();
        jLabelAdministratorPassword = new javax.swing.JLabel();
        jPasswordFieldAdministratorPassword = new javax.swing.JPasswordField();
        btnResetPassword = new javax.swing.JButton();
        jLabelLoginError = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabelCreateedByJacquesSmit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1366, 768));

        jLabelLillyHouseSchoolLibrary.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabelLillyHouseSchoolLibrary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLillyHouseSchoolLibrary.setText("Student Grade Management System");

        jLabelEnterRequiredDetails.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabelEnterRequiredDetails.setForeground(new java.awt.Color(102, 153, 255));
        jLabelEnterRequiredDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEnterRequiredDetails.setText("Enter required details");

        jLabelResetPassword.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelResetPassword.setForeground(new java.awt.Color(0, 153, 255));
        jLabelResetPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResetPassword.setText("Reset password");

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUsername.setText("Username :");

        jTextFieldUsername.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldUsername.setToolTipText("Enter your name");
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        jLabelNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNewPassword.setText("New password :");

        jPasswordFieldNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldNewPasswordActionPerformed(evt);
            }
        });

        jLabelAdministratorPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAdministratorPassword.setText("Administrator Password :");

        jPasswordFieldAdministratorPassword.setToolTipText("Enter administrator password");
        jPasswordFieldAdministratorPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldAdministratorPasswordActionPerformed(evt);
            }
        });

        btnResetPassword.setBackground(new java.awt.Color(0, 153, 255));
        btnResetPassword.setText("Reset password");
        btnResetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPasswordActionPerformed(evt);
            }
        });

        jLabelLoginError.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelLoginError.setForeground(new java.awt.Color(204, 0, 0));
        jLabelLoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLoginError.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("↵ Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabelCreateedByJacquesSmit.setText("Created By Jacques Smit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEnterRequiredDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(517, 517, 517))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(549, 549, 549))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(618, 618, 618)
                        .addComponent(btnResetPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(603, 603, 603)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAdministratorPassword)
                            .addComponent(jPasswordFieldAdministratorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnBack)
                        .addGap(260, 260, 260)
                        .addComponent(jLabelLillyHouseSchoolLibrary))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabelCreateedByJacquesSmit)))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordFieldNewPassword, jTextFieldUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabelLillyHouseSchoolLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabelResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEnterRequiredDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabelNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabelAdministratorPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordFieldAdministratorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabelLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jLabelCreateedByJacquesSmit)
                .addGap(27, 27, 27))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPasswordFieldNewPassword, jTextFieldUsername});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jPasswordFieldNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldNewPasswordActionPerformed

    private void jPasswordFieldAdministratorPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldAdministratorPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldAdministratorPasswordActionPerformed

    /**
     * Handles the action when the 'Reset Password' button is clicked.
     */
    private void btnResetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPasswordActionPerformed
        String username = jTextFieldUsername.getText().trim().toLowerCase(); // Convert to lowercase
        String newPassword = new String(jPasswordFieldNewPassword.getPassword()).trim();
        String adminPassword = new String(jPasswordFieldAdministratorPassword.getPassword()).trim();

        if (username.isEmpty() || newPassword.isEmpty() || adminPassword.isEmpty()) {
            jLabelLoginError.setText("Please fill in all fields.");
            return;
        }

         if (!credentialManager.isAdminPassword(adminPassword)) {
            jLabelLoginError.setText("Incorrect administrator password.");
            return;
        }

        if (credentialManager.resetPassword(username, newPassword)) {
            JOptionPane.showMessageDialog(null,
                    "Password successfully updated. You can now use it to log in.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            LoginPage loginPage = new LoginPage();
            loginPage.setVisible(true);
            dispose();
        } else {
            jLabelLoginError.setText("Username not found.");
        }

    }//GEN-LAST:event_btnResetPasswordActionPerformed

    /**
     * Returns to the LoginPage when the 'Back' button is clicked.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnResetPassword;
    private javax.swing.JLabel jLabelAdministratorPassword;
    private javax.swing.JLabel jLabelCreateedByJacquesSmit;
    private javax.swing.JLabel jLabelEnterRequiredDetails;
    private javax.swing.JLabel jLabelLillyHouseSchoolLibrary;
    private javax.swing.JLabel jLabelLoginError;
    private javax.swing.JLabel jLabelNewPassword;
    private javax.swing.JLabel jLabelResetPassword;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPasswordField jPasswordFieldAdministratorPassword;
    private javax.swing.JPasswordField jPasswordFieldNewPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
