package sgms.ui;

/**
 * @author Jacques Smit
 *
 * SignupPage class allows new users to create an account. It requires
 * administrator password for authorization.
 */
public class SignupPage extends javax.swing.JFrame {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLillyHouseSchoolLibrary = new javax.swing.JLabel();
        jLabelEnterRequiredDetails = new javax.swing.JLabel();
        jLabelCreateAnAccount = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelUsername = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabelYourPassword = new javax.swing.JLabel();
        jLabelAdministratorPassword = new javax.swing.JLabel();
        jPasswordFieldUserPassword = new javax.swing.JPasswordField();
        jPasswordFieldAdministratorPassword = new javax.swing.JPasswordField();
        btnCreateAccount = new javax.swing.JButton();
        jLabelErrorText = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabelCreateedByJacquesSmit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelLillyHouseSchoolLibrary.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabelLillyHouseSchoolLibrary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLillyHouseSchoolLibrary.setText("Student Grade Management System");

        jLabelEnterRequiredDetails.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabelEnterRequiredDetails.setForeground(new java.awt.Color(102, 153, 255));
        jLabelEnterRequiredDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEnterRequiredDetails.setText("Enter required details");

        jLabelCreateAnAccount.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelCreateAnAccount.setForeground(new java.awt.Color(0, 153, 255));
        jLabelCreateAnAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCreateAnAccount.setText("Create an account");

        jLabelName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelName.setText("Name :");

        jTextFieldName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldName.setToolTipText("Enter your name");
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUsername.setText("Username :");

        jTextFieldUsername.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jTextFieldUsername.setToolTipText("Enter your username");
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });

        jLabelYourPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelYourPassword.setText("Your Password :");

        jLabelAdministratorPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelAdministratorPassword.setText("Administrator Password :");

        jPasswordFieldUserPassword.setToolTipText("Enter a strong password");
        jPasswordFieldUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldUserPasswordActionPerformed(evt);
            }
        });

        jPasswordFieldAdministratorPassword.setToolTipText("Enter administrator password");
        jPasswordFieldAdministratorPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldAdministratorPasswordActionPerformed(evt);
            }
        });

        btnCreateAccount.setBackground(new java.awt.Color(0, 153, 255));
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        jLabelErrorText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelErrorText.setForeground(new java.awt.Color(204, 0, 0));
        jLabelErrorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("↵ Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabelCreateedByJacquesSmit.setText("Created By Jacques Smit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLillyHouseSchoolLibrary)
                .addGap(365, 365, 365))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelYourPassword)
                            .addComponent(jPasswordFieldUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAdministratorPassword)
                            .addComponent(jPasswordFieldAdministratorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelEnterRequiredDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCreateAnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(502, 502, 502))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(596, 596, 596)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(608, 608, 608)
                        .addComponent(btnCreateAccount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelCreateedByJacquesSmit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLillyHouseSchoolLibrary, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnBack)))
                .addGap(46, 46, 46)
                .addComponent(jLabelCreateAnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEnterRequiredDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUsername)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelYourPassword)
                    .addComponent(jLabelAdministratorPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldUserPassword)
                    .addComponent(jPasswordFieldAdministratorPassword))
                .addGap(40, 40, 40)
                .addComponent(jLabelErrorText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabelCreateedByJacquesSmit)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jPasswordFieldAdministratorPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldAdministratorPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldAdministratorPasswordActionPerformed

    private void jPasswordFieldUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldUserPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldUserPasswordActionPerformed

    /**
     * Handles the action when the 'Create Account' button is clicked.
     */
    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        String name = jTextFieldName.getText().trim();
        String username = jTextFieldUsername.getText().trim().toLowerCase(); // Convert to lowercase
        String userPassword = new String(jPasswordFieldUserPassword.getPassword()).trim();
        String adminPassword = new String(jPasswordFieldAdministratorPassword.getPassword()).trim();

        if (name.isEmpty() || username.isEmpty() || userPassword.isEmpty() || adminPassword.isEmpty()) {
            jLabelErrorText.setText("Please fill in all fields.");
            return;
        }

        String correctAdminPassword = "admin";

        if (!adminPassword.equals(correctAdminPassword)) {
            jLabelErrorText.setText("Incorrect administrator password.");
            return;
        }

        if (credentialManager.isUsernameExists(username)) {
            jLabelErrorText.setText("Username already exists. Please choose another.");
            return;
        }

        if (credentialManager.addUser(name, username, userPassword)) {
            JOptionPane.showMessageDialog(null,
                    "Account successfully created. You can now use it to log in.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            LoginPage loginPage = new LoginPage();
            loginPage.setVisible(true);
            dispose();
        } else {
            jLabelErrorText.setText("Error occurred. Could not create the account.");
        }

    }//GEN-LAST:event_btnCreateAccountActionPerformed

    /**
     * Returns to the LoginPage when the 'Back' button is clicked.
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JLabel jLabelAdministratorPassword;
    private javax.swing.JLabel jLabelCreateAnAccount;
    private javax.swing.JLabel jLabelCreateedByJacquesSmit;
    private javax.swing.JLabel jLabelEnterRequiredDetails;
    private javax.swing.JLabel jLabelErrorText;
    private javax.swing.JLabel jLabelLillyHouseSchoolLibrary;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelYourPassword;
    private javax.swing.JPasswordField jPasswordFieldAdministratorPassword;
    private javax.swing.JPasswordField jPasswordFieldUserPassword;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
